// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppDam.Models;

#nullable disable

namespace WebAppDam.Migrations
{
    [DbContext(typeof(ITIContext))]
    [Migration("20260112082623_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppDam.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerName = "Ahmed",
                            Name = "SD"
                        },
                        new
                        {
                            Id = 2,
                            ManagerName = "Mohamed",
                            Name = "UI"
                        },
                        new
                        {
                            Id = 3,
                            ManagerName = "Khaled",
                            Name = "OS"
                        });
                });

            modelBuilder.Entity("WebAppDam.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "Ahemd@gmail.com",
                            ImageUrl = "m.png",
                            Name = "Ahmed",
                            Salary = 10000
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "Ahemd@gmail.com",
                            ImageUrl = "m.png",
                            Name = "Ali",
                            Salary = 20000
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "Ahemd@gmail.com",
                            ImageUrl = "2.jpg",
                            Name = "Sara",
                            Salary = 30000
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Email = "Ahemd@gmail.com",
                            ImageUrl = "2.jpg",
                            Name = "Hala",
                            Salary = 40000
                        });
                });

            modelBuilder.Entity("WebAppDam.Models.Employee", b =>
                {
                    b.HasOne("WebAppDam.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WebAppDam.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
